[2023-11-21T17:17:57.701+0900] {processor.py:157} INFO - Started process (PID=35723) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:17:57.701+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:17:57.702+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:17:57.702+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:17:57.706+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:17:57.705+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:17:57.706+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:17:57.723+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:18:28.643+0900] {processor.py:157} INFO - Started process (PID=35758) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:18:28.643+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:18:28.644+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:18:28.644+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:18:28.648+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:18:28.647+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:18:28.648+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:18:28.665+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.025 seconds
[2023-11-21T17:19:13.643+0900] {processor.py:157} INFO - Started process (PID=35809) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:13.645+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:19:13.646+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:19:13.645+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:13.649+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:19:13.648+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:19:13.649+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:13.670+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.030 seconds
[2023-11-21T17:19:55.415+0900] {processor.py:157} INFO - Started process (PID=35858) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:55.416+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:19:55.417+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:19:55.416+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:55.421+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:19:55.420+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:19:55.421+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:19:55.439+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:20:38.566+0900] {processor.py:157} INFO - Started process (PID=35919) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:20:38.567+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:20:38.568+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:20:38.568+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:20:38.572+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:20:38.571+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:20:38.572+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:20:38.590+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:21:18.760+0900] {processor.py:157} INFO - Started process (PID=35967) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:18.762+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:21:18.762+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:21:18.762+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:18.766+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:21:18.765+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:21:18.766+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:18.784+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:21:55.616+0900] {processor.py:157} INFO - Started process (PID=36008) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:55.618+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:21:55.619+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:21:55.618+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:55.622+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:21:55.621+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:21:55.622+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:21:55.640+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:22:36.749+0900] {processor.py:157} INFO - Started process (PID=36090) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:22:36.750+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:22:36.751+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:22:36.750+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:22:36.754+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:22:36.753+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:22:36.755+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:22:36.771+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:23:17.973+0900] {processor.py:157} INFO - Started process (PID=36139) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:17.974+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:23:17.974+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:23:17.974+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:17.978+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:23:17.977+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:23:17.978+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:17.996+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:23:59.747+0900] {processor.py:157} INFO - Started process (PID=36184) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:59.748+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:23:59.749+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:23:59.749+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:59.753+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:23:59.752+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:23:59.753+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:23:59.770+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:24:41.523+0900] {processor.py:157} INFO - Started process (PID=36244) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:24:41.525+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:24:41.525+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:24:41.525+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:24:41.529+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:24:41.528+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:24:41.529+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:24:41.548+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:25:22.083+0900] {processor.py:157} INFO - Started process (PID=36303) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:25:22.084+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:25:22.085+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:25:22.084+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:25:22.088+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:25:22.087+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:25:22.089+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:25:22.106+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:26:02.744+0900] {processor.py:157} INFO - Started process (PID=36351) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:02.746+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:26:02.746+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:26:02.746+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:02.750+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:26:02.749+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:26:02.750+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:02.767+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:26:42.131+0900] {processor.py:157} INFO - Started process (PID=36393) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:42.132+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:26:42.133+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:26:42.133+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:42.137+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:26:42.136+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:26:42.137+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:26:42.155+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:27:24.400+0900] {processor.py:157} INFO - Started process (PID=36442) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:27:24.402+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:27:24.402+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:27:24.402+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:27:24.406+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:27:24.405+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:27:24.406+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:27:24.424+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:28:03.711+0900] {processor.py:157} INFO - Started process (PID=36490) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:03.712+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:28:03.713+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:28:03.712+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:03.716+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:28:03.715+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:28:03.717+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:03.733+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:28:47.642+0900] {processor.py:157} INFO - Started process (PID=36535) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:47.643+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:28:47.644+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:28:47.643+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:47.647+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:28:47.646+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:28:47.648+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:28:47.665+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:29:29.220+0900] {processor.py:157} INFO - Started process (PID=36585) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:29:29.221+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:29:29.222+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:29:29.222+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:29:29.226+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:29:29.225+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:29:29.226+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:29:29.243+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:30:09.343+0900] {processor.py:157} INFO - Started process (PID=36632) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:09.344+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:30:09.345+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:30:09.345+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:09.349+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:30:09.348+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:30:09.349+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:09.380+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.040 seconds
[2023-11-21T17:30:50.374+0900] {processor.py:157} INFO - Started process (PID=36675) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:50.375+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:30:50.376+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:30:50.375+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:50.379+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:30:50.378+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:30:50.379+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:30:50.397+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:31:34.175+0900] {processor.py:157} INFO - Started process (PID=36723) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:31:34.176+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:31:34.177+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:31:34.177+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:31:34.180+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:31:34.180+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:31:34.181+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:31:34.198+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:32:14.268+0900] {processor.py:157} INFO - Started process (PID=36773) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:14.269+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:32:14.270+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:32:14.270+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:14.274+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:32:14.273+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:32:14.274+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:14.291+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:32:50.640+0900] {processor.py:157} INFO - Started process (PID=36813) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:50.641+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:32:50.642+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:32:50.641+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:50.645+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:32:50.644+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:32:50.645+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:32:50.663+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:33:32.277+0900] {processor.py:157} INFO - Started process (PID=36860) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:33:32.278+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:33:32.279+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:33:32.279+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:33:32.283+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:33:32.282+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:33:32.283+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:33:32.301+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:34:13.546+0900] {processor.py:157} INFO - Started process (PID=36913) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:13.548+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:34:13.548+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:34:13.548+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:13.552+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:34:13.551+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:34:13.552+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:13.570+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:34:51.632+0900] {processor.py:157} INFO - Started process (PID=36954) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:51.633+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:34:51.634+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:34:51.633+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:51.637+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:34:51.636+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:34:51.637+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:34:51.655+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:35:34.326+0900] {processor.py:157} INFO - Started process (PID=37003) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:35:34.327+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:35:34.328+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:35:34.328+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:35:34.332+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:35:34.331+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:35:34.332+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:35:34.350+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:36:18.225+0900] {processor.py:157} INFO - Started process (PID=37086) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:18.226+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:36:18.227+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:36:18.226+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:18.230+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:36:18.229+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:36:18.231+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:18.248+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:36:59.716+0900] {processor.py:157} INFO - Started process (PID=37129) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:59.717+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:36:59.718+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:36:59.718+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:59.722+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:36:59.721+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:36:59.722+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:36:59.740+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:37:41.637+0900] {processor.py:157} INFO - Started process (PID=37177) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:37:41.638+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:37:41.639+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:37:41.638+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:37:41.642+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:37:41.641+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:37:41.642+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:37:41.660+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:38:22.827+0900] {processor.py:157} INFO - Started process (PID=37228) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:38:22.829+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:38:22.829+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:38:22.829+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:38:22.833+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:38:22.832+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:38:22.833+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:38:22.851+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:39:03.781+0900] {processor.py:157} INFO - Started process (PID=37279) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:03.782+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:39:03.783+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:39:03.782+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:03.786+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:39:03.785+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:39:03.787+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:03.805+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:39:43.943+0900] {processor.py:157} INFO - Started process (PID=37323) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:43.944+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:39:43.944+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:39:43.944+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:43.948+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:39:43.947+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:39:43.948+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:39:43.966+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:40:22.929+0900] {processor.py:157} INFO - Started process (PID=37369) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:40:22.930+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:40:22.931+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:40:22.930+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:40:22.934+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:40:22.934+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:40:22.935+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:40:22.952+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:41:03.967+0900] {processor.py:157} INFO - Started process (PID=37418) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:03.968+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:41:03.969+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:41:03.968+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:03.972+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:41:03.971+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:41:03.973+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:03.990+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:41:44.597+0900] {processor.py:157} INFO - Started process (PID=37460) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:44.598+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:41:44.598+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:41:44.598+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:44.602+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:41:44.601+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:41:44.602+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:41:44.619+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:42:25.762+0900] {processor.py:157} INFO - Started process (PID=37510) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:42:25.763+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:42:25.764+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:42:25.764+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:42:25.768+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:42:25.767+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:42:25.768+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:42:25.785+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:43:03.177+0900] {processor.py:157} INFO - Started process (PID=37554) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:03.178+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:43:03.179+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:43:03.178+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:03.183+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:43:03.182+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:43:03.183+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:03.201+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:43:42.979+0900] {processor.py:157} INFO - Started process (PID=37598) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:42.980+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:43:42.981+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:43:42.980+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:42.984+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:43:42.983+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:43:42.985+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:43:43.002+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T17:44:25.479+0900] {processor.py:157} INFO - Started process (PID=37648) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:44:25.481+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:44:25.481+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:44:25.481+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:44:25.485+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:44:25.484+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:44:25.485+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:44:25.503+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:45:06.653+0900] {processor.py:157} INFO - Started process (PID=37696) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:06.655+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:45:06.655+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:45:06.655+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:06.659+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:45:06.658+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:45:06.659+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:06.677+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T17:45:46.211+0900] {processor.py:157} INFO - Started process (PID=37740) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:46.212+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T17:45:46.213+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:45:46.212+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:46.216+0900] {logging_mixin.py:154} INFO - [2023-11-21T17:45:46.215+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T17:45:46.216+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T17:45:46.234+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:09:25.010+0900] {processor.py:157} INFO - Started process (PID=1120) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:09:25.011+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:09:25.012+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:09:25.012+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:09:25.017+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:09:25.016+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:09:25.017+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:09:25.037+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:10:15.117+0900] {processor.py:157} INFO - Started process (PID=1468) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:15.118+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:10:15.119+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:10:15.119+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:15.123+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:10:15.122+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:10:15.123+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:15.141+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:10:56.256+0900] {processor.py:157} INFO - Started process (PID=1514) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:56.257+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:10:56.258+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:10:56.257+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:56.261+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:10:56.260+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:10:56.261+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:10:56.280+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:11:37.466+0900] {processor.py:157} INFO - Started process (PID=1561) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:11:37.467+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:11:37.468+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:11:37.468+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:11:37.472+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:11:37.471+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:11:37.472+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:11:37.490+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:12:18.770+0900] {processor.py:157} INFO - Started process (PID=1609) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:18.771+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:12:18.772+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:12:18.771+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:18.775+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:12:18.774+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:12:18.776+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:18.794+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:12:59.895+0900] {processor.py:157} INFO - Started process (PID=1657) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:59.896+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:12:59.897+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:12:59.896+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:59.901+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:12:59.900+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:12:59.901+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:12:59.925+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.034 seconds
[2023-11-21T20:13:39.416+0900] {processor.py:157} INFO - Started process (PID=1705) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:13:39.418+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:13:39.419+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:13:39.418+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:13:39.422+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:13:39.421+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:13:39.423+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:13:39.441+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:14:17.204+0900] {processor.py:157} INFO - Started process (PID=1751) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:17.206+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:14:17.207+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:14:17.206+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:17.211+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:14:17.210+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:14:17.211+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:17.232+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:14:56.925+0900] {processor.py:157} INFO - Started process (PID=2009) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:56.926+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:14:56.927+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:14:56.927+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:56.931+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:14:56.930+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:14:56.932+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:14:56.951+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.030 seconds
[2023-11-21T20:15:38.704+0900] {processor.py:157} INFO - Started process (PID=2058) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:15:38.705+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:15:38.706+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:15:38.706+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:15:38.710+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:15:38.709+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:15:38.710+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:15:38.731+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.030 seconds
[2023-11-21T20:16:19.839+0900] {processor.py:157} INFO - Started process (PID=2109) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:19.840+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:16:19.842+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:16:19.841+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:19.847+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:16:19.846+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:16:19.848+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:19.868+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.034 seconds
[2023-11-21T20:16:58.313+0900] {processor.py:157} INFO - Started process (PID=2153) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:58.314+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:16:58.315+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:16:58.315+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:58.319+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:16:58.318+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:16:58.319+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:16:58.338+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:17:33.562+0900] {processor.py:157} INFO - Started process (PID=2201) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:17:33.564+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:17:33.565+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:17:33.564+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:17:33.569+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:17:33.568+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:17:33.569+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:17:33.588+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.029 seconds
[2023-11-21T20:18:12.074+0900] {processor.py:157} INFO - Started process (PID=2249) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:12.075+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:18:12.076+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:18:12.075+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:12.079+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:18:12.078+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:18:12.079+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:12.097+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:18:50.111+0900] {processor.py:157} INFO - Started process (PID=2289) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:50.112+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:18:50.113+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:18:50.112+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:50.116+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:18:50.116+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:18:50.117+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:18:50.136+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.029 seconds
[2023-11-21T20:19:32.109+0900] {processor.py:157} INFO - Started process (PID=2339) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:19:32.110+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:19:32.110+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:19:32.110+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:19:32.114+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:19:32.113+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:19:32.114+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:19:32.133+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:20:11.775+0900] {processor.py:157} INFO - Started process (PID=2385) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:11.776+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:20:11.777+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:20:11.777+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:11.781+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:20:11.780+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:20:11.781+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:11.805+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.034 seconds
[2023-11-21T20:20:51.723+0900] {processor.py:157} INFO - Started process (PID=2429) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:51.724+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:20:51.725+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:20:51.725+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:51.729+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:20:51.728+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:20:51.729+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:20:51.748+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:21:25.199+0900] {processor.py:157} INFO - Started process (PID=2473) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:21:25.200+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:21:25.201+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:21:25.201+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:21:25.205+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:21:25.204+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:21:25.205+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:21:25.223+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:22:01.009+0900] {processor.py:157} INFO - Started process (PID=2512) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:01.010+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:22:01.011+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:22:01.011+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:01.015+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:22:01.014+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:22:01.015+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:01.033+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:22:40.974+0900] {processor.py:157} INFO - Started process (PID=2561) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:40.976+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:22:40.976+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:22:40.976+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:40.980+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:22:40.979+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:22:40.980+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:22:40.999+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:23:18.975+0900] {processor.py:157} INFO - Started process (PID=2608) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:23:18.976+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:23:18.977+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:23:18.977+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:23:18.981+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:23:18.980+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:23:18.981+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:23:18.999+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:24:01.906+0900] {processor.py:157} INFO - Started process (PID=2681) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:01.907+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:24:01.908+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:24:01.908+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:01.911+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:24:01.911+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:24:01.912+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:01.930+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:24:41.454+0900] {processor.py:157} INFO - Started process (PID=2730) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:41.455+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:24:41.456+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:24:41.456+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:41.460+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:24:41.459+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:24:41.460+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:24:41.479+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:25:19.077+0900] {processor.py:157} INFO - Started process (PID=2775) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:19.078+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:25:19.079+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:25:19.079+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:19.083+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:25:19.082+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:25:19.083+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:19.101+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:25:59.303+0900] {processor.py:157} INFO - Started process (PID=2818) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:59.304+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:25:59.305+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:25:59.305+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:59.308+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:25:59.308+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:25:59.309+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:25:59.326+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:26:41.037+0900] {processor.py:157} INFO - Started process (PID=2866) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:26:41.038+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:26:41.038+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:26:41.038+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:26:41.042+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:26:41.041+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:26:41.042+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:26:41.060+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:27:22.830+0900] {processor.py:157} INFO - Started process (PID=2915) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:27:22.831+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:27:22.832+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:27:22.831+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:27:22.836+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:27:22.835+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:27:22.836+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:27:22.855+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:28:02.247+0900] {processor.py:157} INFO - Started process (PID=2965) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:02.248+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:28:02.248+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:28:02.248+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:02.252+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:28:02.251+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:28:02.252+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:02.277+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.034 seconds
[2023-11-21T20:28:42.068+0900] {processor.py:157} INFO - Started process (PID=3008) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:42.069+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:28:42.070+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:28:42.070+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:42.074+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:28:42.073+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:28:42.074+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:28:42.092+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:29:24.242+0900] {processor.py:157} INFO - Started process (PID=3169) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:29:24.243+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:29:24.244+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:29:24.244+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:29:24.247+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:29:24.247+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:29:24.248+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:29:24.266+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:30:07.455+0900] {processor.py:157} INFO - Started process (PID=3233) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:07.456+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:30:07.457+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:30:07.457+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:07.461+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:30:07.460+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:30:07.461+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:07.479+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:30:50.729+0900] {processor.py:157} INFO - Started process (PID=3276) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:50.730+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:30:50.731+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:30:50.731+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:50.736+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:30:50.735+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:30:50.737+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:30:50.756+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:31:34.870+0900] {processor.py:157} INFO - Started process (PID=3382) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:31:34.871+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:31:34.872+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:31:34.872+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:31:34.876+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:31:34.875+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:31:34.876+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:31:34.896+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.029 seconds
[2023-11-21T20:32:15.290+0900] {processor.py:157} INFO - Started process (PID=3429) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:15.292+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:32:15.292+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:32:15.292+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:15.296+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:32:15.295+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:32:15.296+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:15.315+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:32:55.313+0900] {processor.py:157} INFO - Started process (PID=3473) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:55.314+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:32:55.315+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:32:55.315+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:55.319+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:32:55.318+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:32:55.319+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:32:55.336+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:33:36.602+0900] {processor.py:157} INFO - Started process (PID=3520) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:33:36.603+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:33:36.604+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:33:36.604+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:33:36.608+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:33:36.607+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:33:36.608+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:33:36.626+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:34:20.136+0900] {processor.py:157} INFO - Started process (PID=3588) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:34:20.137+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:34:20.137+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:34:20.137+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:34:20.141+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:34:20.140+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:34:20.141+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:34:20.159+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:35:02.370+0900] {processor.py:157} INFO - Started process (PID=3637) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:02.371+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:35:02.372+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:35:02.372+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:02.376+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:35:02.375+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:35:02.376+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:02.394+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:35:42.488+0900] {processor.py:157} INFO - Started process (PID=3681) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:42.489+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:35:42.490+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:35:42.490+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:42.493+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:35:42.492+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 22
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2023-11-21T20:35:42.494+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:35:42.512+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:36:24.862+0900] {processor.py:157} INFO - Started process (PID=3733) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:36:24.863+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:36:24.864+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:36:24.864+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:36:24.867+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:36:24.866+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 22
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2023-11-21T20:36:24.867+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:36:24.885+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:37:01.966+0900] {processor.py:157} INFO - Started process (PID=3778) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:01.967+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:37:01.968+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:01.967+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:01.971+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:01.970+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 22
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2023-11-21T20:37:01.971+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:01.992+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.030 seconds
[2023-11-21T20:37:22.025+0900] {processor.py:157} INFO - Started process (PID=3801) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:22.026+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:37:22.027+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:22.026+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:22.030+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:22.029+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 22
    ) as dag:
            ^
SyntaxError: unexpected EOF while parsing
[2023-11-21T20:37:22.030+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:22.048+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:37:45.427+0900] {processor.py:157} INFO - Started process (PID=3828) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:45.428+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:37:45.428+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:45.428+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:45.433+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:37:45.432+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:37:45.433+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:37:45.452+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.029 seconds
[2023-11-21T20:38:28.934+0900] {processor.py:157} INFO - Started process (PID=3878) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:38:28.936+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:38:28.936+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:38:28.936+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:38:28.941+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:38:28.940+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:38:28.941+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:38:28.959+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:39:14.344+0900] {processor.py:157} INFO - Started process (PID=3928) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:14.345+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:39:14.346+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:39:14.345+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:14.349+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:39:14.348+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:39:14.350+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:14.368+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:39:58.614+0900] {processor.py:157} INFO - Started process (PID=3973) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:58.615+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:39:58.616+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:39:58.616+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:58.620+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:39:58.619+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:39:58.621+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:39:58.638+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:40:47.531+0900] {processor.py:157} INFO - Started process (PID=4027) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:40:47.532+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:40:47.533+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:40:47.533+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:40:47.548+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:40:47.547+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:40:47.548+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:40:47.587+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.060 seconds
[2023-11-21T20:41:11.958+0900] {processor.py:157} INFO - Started process (PID=4054) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:11.959+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:41:11.960+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:41:11.960+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:11.964+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:41:11.963+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:41:11.964+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:11.985+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:41:53.125+0900] {processor.py:157} INFO - Started process (PID=4189) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:53.126+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:41:53.127+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:41:53.126+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:53.130+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:41:53.129+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:41:53.130+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:41:53.149+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:42:33.533+0900] {processor.py:157} INFO - Started process (PID=4237) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:42:33.534+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:42:33.535+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:42:33.535+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:42:33.538+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:42:33.538+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:42:33.539+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:42:33.557+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:43:15.017+0900] {processor.py:157} INFO - Started process (PID=4284) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:15.019+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:43:15.020+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:43:15.019+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:15.023+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:43:15.022+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:43:15.023+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:15.042+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:43:54.414+0900] {processor.py:157} INFO - Started process (PID=4345) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:54.415+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:43:54.415+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:43:54.415+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:54.419+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:43:54.418+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:43:54.419+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:43:54.437+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:44:36.565+0900] {processor.py:157} INFO - Started process (PID=4438) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:44:36.566+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:44:36.567+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:44:36.566+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:44:36.570+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:44:36.569+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:44:36.570+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:44:36.588+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:45:20.571+0900] {processor.py:157} INFO - Started process (PID=4503) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:45:20.572+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:45:20.573+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:45:20.573+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:45:20.576+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:45:20.575+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:45:20.577+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:45:20.596+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:46:04.423+0900] {processor.py:157} INFO - Started process (PID=4553) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:04.424+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:46:04.425+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:46:04.425+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:04.429+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:46:04.428+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:46:04.430+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:04.448+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.028 seconds
[2023-11-21T20:46:25.365+0900] {processor.py:157} INFO - Started process (PID=4576) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:25.366+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:46:25.366+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:46:25.366+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:25.370+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:46:25.369+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:46:25.370+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:46:25.388+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:47:07.501+0900] {processor.py:157} INFO - Started process (PID=4623) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:07.502+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:47:07.503+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:47:07.503+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:07.506+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:47:07.505+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:47:07.506+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:07.524+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:47:51.290+0900] {processor.py:157} INFO - Started process (PID=4671) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:51.291+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:47:51.292+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:47:51.292+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:51.295+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:47:51.294+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:47:51.295+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:47:51.313+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:48:36.105+0900] {processor.py:157} INFO - Started process (PID=4721) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:48:36.106+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:48:36.107+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:48:36.107+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:48:36.110+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:48:36.109+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:48:36.111+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:48:36.128+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:49:22.979+0900] {processor.py:157} INFO - Started process (PID=4779) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:49:22.980+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:49:22.981+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:49:22.981+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:49:22.984+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:49:22.983+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:49:22.984+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:49:23.002+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:50:07.231+0900] {processor.py:157} INFO - Started process (PID=4829) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:07.232+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:50:07.233+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:50:07.233+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:07.236+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:50:07.236+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:50:07.237+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:07.259+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:50:48.410+0900] {processor.py:157} INFO - Started process (PID=4878) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:48.411+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:50:48.412+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:50:48.412+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:48.415+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:50:48.414+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:50:48.416+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:50:48.433+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:51:34.151+0900] {processor.py:157} INFO - Started process (PID=4932) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:51:34.153+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:51:34.153+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:51:34.153+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:51:34.157+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:51:34.156+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 27
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:51:34.157+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:51:34.174+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:52:17.718+0900] {processor.py:157} INFO - Started process (PID=4979) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:17.719+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:52:17.720+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:52:17.719+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:17.723+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:52:17.722+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 39
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:52:17.723+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:17.741+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:52:39.235+0900] {processor.py:157} INFO - Started process (PID=5004) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:39.236+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:52:39.237+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:52:39.236+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:39.240+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:52:39.239+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 39
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:52:39.240+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:52:39.258+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:53:20.140+0900] {processor.py:157} INFO - Started process (PID=5051) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:20.141+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:53:20.142+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:53:20.142+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:20.145+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:53:20.144+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 39
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:53:20.146+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:20.163+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.026 seconds
[2023-11-21T20:53:40.631+0900] {processor.py:157} INFO - Started process (PID=5075) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:40.632+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:53:40.632+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:53:40.632+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:40.636+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:53:40.635+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 37
    python_callable= = get_musinsa
                     ^
SyntaxError: invalid syntax
[2023-11-21T20:53:40.636+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:53:40.654+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:54:03.341+0900] {processor.py:157} INFO - Started process (PID=5101) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:03.342+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:54:03.343+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:54:03.343+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:03.348+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:54:03.347+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:54:03.349+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:03.368+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.030 seconds
[2023-11-21T20:54:46.755+0900] {processor.py:157} INFO - Started process (PID=5147) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:46.756+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:54:46.757+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:54:46.756+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:46.761+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:54:46.760+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:54:46.762+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:54:46.782+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.031 seconds
[2023-11-21T20:55:29.343+0900] {processor.py:157} INFO - Started process (PID=5196) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:55:29.344+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:55:29.345+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:55:29.345+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:55:29.349+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:55:29.348+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:55:29.349+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:55:29.367+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
[2023-11-21T20:56:10.137+0900] {processor.py:157} INFO - Started process (PID=5254) to work on /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:56:10.138+0900] {processor.py:829} INFO - Processing file /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py for tasks to queue
[2023-11-21T20:56:10.139+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:56:10.139+0900] {dagbag.py:536} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:56:10.143+0900] {logging_mixin.py:154} INFO - [2023-11-21T20:56:10.142+0900] {dagbag.py:346} ERROR - Failed to import: /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py", line 4, in <module>
    from crawler.musinsa_examples import get_musinsa
ModuleNotFoundError: No module named 'crawler.musinsa_examples'
[2023-11-21T20:56:10.143+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py
[2023-11-21T20:56:10.161+0900] {processor.py:179} INFO - Processing /home/ubuntu/airflow/dags/study/06_musinsa_soup_pipeline.py took 0.027 seconds
